### ISSUE TITLE
Clase 6

### ISSUE THREAD

**Issue by eugenia1984** [CodeSystem2022/ERROR404-METODOLOGIA-DE-SISTEMAS#13]
- Clase 6 de Node y de Java
- Dev.: M. Eugenia, Costa
- Scrum: Rodrigo, Chavez

**Comment by eugenia1984** [comment]
- Creo la rama **release/1.0.0** para subir la clase 6

- Creo la carpeta node_clase6 y subo ahí el código de node

**Comment by eugenia1984** [comment]
- Creo la carpeta **clase_06_tienda_libro** y subo le proyecto de Java

- @RodrigoChavez1986 ya deje el merge request

**Comment by RodrigoChavez1986** [comment]
Código de clase 6 OK
