### ISSUE TITLE
Clase 2 - 23 AUG

### ISSUE THREAD

**Issue by eugenia1984** [CodeSystem2022/ERROR404-METODOLOGIA-DE-SISTEMAS#3]
Subir clase de  Miércoles 23 Agosto: Aplicación de Sistema Estudiantes con Spring Boot -> Parte 1(Java) / Hola Mundo desde Node y algo más...

**Comment by eugenia1984** [comment]
@LucasNavarro01 falta lo de node, solo vi lo de Java, puede ser?

**Comment by LucasNavarro01** [comment]
Ahi cree y subí la carpeta con la clase de Node

**Comment by eugenia1984** [comment]
Listo cierro ese issue porque agregamos en main lo de node
